language: java

jdk:
  - openjdk16

install: true

script: mvn clean package -DskipTests=true

notifications:
  email:
    recipients:
      - glavstroi_e@mail.ru
    on_success: never
    on_failure: always